### ISSUE TITLE
Corruption name is not displayed in Encounter Journal loot tooltip

### ISSUE THREAD

**Issue by RainmakerUA** [suspectz/Corruption-Tooltips#14]
I guess it is pretty clear from the screenshot (sorry for Russian client, was too lazy to restart it in English):
![image](https://user-images.githubusercontent.com/1702751/74884198-490ea200-537b-11ea-8ec8-28e5394704a0.png)
Short investigation showed that you need to catch ADDON_LOADED event for Blizzard_EncounterJournal addon and hook somewhere inside EncounterJournalTooltip global (it has tooltip as property inside)

**Comment by suspectz** [comment]
I actually already followed this route to try and figure out why, but the code is already running. The normal GameTooltip code runs, and the check if the item is corrupted is fine.

The reason it can't get the applied corruption is because the itemLink has an incomplete set of bonus IDs (1 rather than 6). Missing is the bonus IDs for the relevant corruption.

Any further ideas? I'll see today if anyone else has documented a solution to that, but all examples I've seen only care about the itemid.

**Comment by suspectz** [comment]
Ok, I have a fix for this. It'll be in the next version 1.6.6

**Comment by suspectz** [comment]
Please check if 1.6.6 fixes this issue for you. Thanks in advance.

**Comment by RainmakerUA** [comment]
Pretty straightforward approach. But it did the thing 👍 
Thank you
