### ISSUE TITLE
zhTW is missing from the localization

### ISSUE THREAD

**Issue by BlueNightSky** [suspectz/Corruption-Tooltips#2]
zhTW is missing from the localization:
L["Corruption"] = "腐化"

By the way,
I added it manually, but it doesn't seem to show the position next to the corruption.
See screenshot for details:
https://imgur.com/oXvWHxo

**Comment by suspectz** [comment]
Thanks for this. I see you've got a typo in your pull that has it as znTW, rather than zhTW for the if statement. Looks like you copied over my typo in znCN. I can push a version with both fixed, but can you confirm it's working for you after those changes? I can't use the client in znTW or znCH because I can't login to English realms and look at a corrupt item.

Thanks for the help!

**Comment by BlueNightSky** [comment]
I'm really presbyopic and didn't notice the misspelling, but after the correction, the tooltip is still displayed at the bottom instead of next to "Corruption", don't know where the problem is.
In addition, zhTW is still missing in locales.xml, but I have manually added.

**Comment by suspectz** [comment]
I believe the issue is either due to the lua string matching not being happy with utf-8 (doubtful), or its because I was specifically searching for +<number><space><translation>. Your screenshots show no <space>. I also had issues with not matching RU because they have another char inbetween, so I've changed it in v1.5 to a simple string.find. If the translation is correct, it should find it - I hope.

**Comment by BlueNightSky** [comment]
Good news, after using the latest version, it can be displayed correctly next to Corruption. ^_^
